### ISSUE TITLE
grammar preprocessor statements

### ISSUE THREAD

**Issue by sertonix** [zyedidia/flare#11]
Preprocessor statements could make grammars more readable and allow passing arguments when using/including a grammar.
My idea would be to have similar things to C. So `id`, `define` and `makro`.
They can also be used to customize the include of other grammars to eg. fix wrong highlighting.

For markdown this could look something like this:
```rb
block <- '```' (!"\n" .)* (!'```' .)* '```'?

# highlight code blocks if not disabled
$ifndef disable_code_highlighting

# disable code highlighting for markdown in code block
$define disable_code_highlighting

$makro BLOCK(LANG, CODE) CODE <- include{"LANG"} \
    CODEblock <- '```CODE' (!'```' (CODE / (. (!CODE .)*)))* '```'?

BLOCK(markdown, md)

code <- mdblock / block

$endif

code <- block
```
(This example is not that realistic)

They would also not really extend the syntax since the result of the preprocessor will be as before.

(This issue may be better at `gpeg`)

**Comment by zyedidia** [comment]
I'm not sure that grammars have enough repetition to warrant something like this. It seems to add a lot of complexity for little benefit.

**Comment by sertonix** [comment]
Ok, was just an idea
