### ISSUE TITLE
partial highlight

### ISSUE THREAD

**Issue by sertonix** [zyedidia/flare#3]
If possible (I don't know if it is) it would be nice to implement the highlighting of incomplete code without making the `.lang` files more complicated.

Maybe that the end of the file matches anything instead of nothing.

**Comment by zyedidia** [comment]
Could you give an example? I think flare should currently handle highlighting incomplete code.

**Comment by sertonix** [comment]
### Example

grammar:
```peg
token <- cap{ '"' (!'"' .)* '"', "constant.string" }
```

test file:
```js
"highlighted"
"not highlighted
```

When the grammar is changed a bit the highlighting would work but I would like if this is not required.
```peg
token <- cap{ '"' (!'"' .)* '"'?, "constant.string" }
```

**Comment by sertonix** [comment]
Thinking about it a bit more. Trying to autodetect what is not complete yet might cause more harm than it helps. There is no good rule I can think of.

**Comment by zyedidia** [comment]
Yeah I think you just need to include the `?` if you want it to highlight an in-progress string.

**Comment by sertonix** [comment]
@zyedidia (I hope it is ok if I abuse this issue for some chat)
I would like to know the state of this project. Especially the implementation in `micro`.
If contributing themes and grammars would help I would be glad to do that.
I currently don't know Go so I can't really help with the actuall code. Learning Go is an my TODO list though.

I am not the best at writing texts but I could also try to add some documentation to the project. Things like the syntax of the grammars would be important.

**Comment by zyedidia** [comment]
New grammars would be very helpful! It would be good to have support for as many of the current micro languages as possible, with preference towards languages that are most widely used.

Also support for all the current default micro themes would be great! Thank you for any amount of effort you contribute to the project! It might be awhile before we can integrate this into micro but I hope to do it at some point.
